# Generated by Django 3.1.1 on 2020-09-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20200911_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionPedidos.clientes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionPedidos.articulos'),
        ),
    ]
