# Generated by Django 3.1.1 on 2020-09-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(verbose_name='Contanos que te parecio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/%Y/%m/%d', verbose_name='Subi una foto del producto!'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
