# Generated by Django 3.1.1 on 2020-09-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=1000, verbose_name='Informacion del producto'),
        ),
    ]
